excluded:
  - Carthage
  - Pods
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_types_order
  - first_where
  - identical_operands
  - implicit_return
  - last_where
  - legacy_random
  - let_var_whitespace
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - redundant_type_annotation
  - sorted_first_last
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unused_enumerated
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - yoda_condition

disabled_rules:
  - trailing_newline
  - trailing_whitespace
  - todo # включить перед первым релизом!
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity

identifier_name:
  severity: warning
  min_length: 2 # only warning

class_delegate_protocol:
  severity: error

deployment_target:
  iOS_deployment_target: 11

multiline_arguments:
  first_argument_location: next_line

attributes:
  always_on_same_line: ["@IBAction", "@NSManaged", "@objc"]

